/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/XevXOaFXPuX
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";
import { Button } from "@/components/ui/button";
import {
  DialogTrigger,
  DialogTitle,
  DialogDescription,
  DialogHeader,
  DialogFooter,
  DialogContent,
  Dialog,
} from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { useEffect, useState } from "react";

export function SendNotification({ match, open, onChange }) {
  const [title, setTitle] = useState("");
  const [body, setBody] = useState("");
  useEffect(() => {
    setTitle(`New NFL Match: ${match.team1} vs ${match.team2}`);
    const date = new Date(match.date).toLocaleDateString();
    setBody(
      `Match between ${match.team1} and ${match.team2} is scheduled on ${date} at ${match.time}`
    );
  }, [match]);
  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const response = await fetch(`/api/send-notification`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ title, body }),
      });
      if (!response.ok) throw new Error("Network response was not ok");
      const data = await response.json();
      alert("Notification sent successfully!");
      onChange();
    } catch (error) {
      console.error("Failed to add channel", error);
      alert("Failed to add channel: " + error.message);
    }
  };
  return (
    <Dialog open={open} onOpenChange={onChange}>
      <DialogTrigger asChild></DialogTrigger>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>Send Notification</DialogTitle>
          <DialogDescription>
            Send a notification to all users subscribed to the NFL topic.
          </DialogDescription>
        </DialogHeader>
        <div className="grid gap-4 py-4">
          <div className="grid grid-cols-4 items-center gap-4">
            <Label className="text-right" htmlFor="notification-title">
              Title
            </Label>
            <Input
              className="col-span-3"
              id="notification-title"
              placeholder="Enter notification title"
              onChange={(e) => setTitle(e.target.value)}
              value={title}
            />
          </div>
          <div className="grid grid-cols-4 items-center gap-4">
            <Label className="text-right" htmlFor="notification-body">
              Body
            </Label>
            <Input
              className="col-span-3"
              id="notification-body"
              placeholder="Enter notification body"
              onChange={(e) => setBody(e.target.value)}
              value={body}
            />
          </div>
        </div>
        <DialogFooter>
          <Button className="mr-2" variant="outline">
            Cancel
          </Button>
          <Button type="submit" onClick={handleSubmit}>
            Save
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
